server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

logging:
  file:
    name: ../../logs/eureka.log
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 100MB
      total-size-cap: 100MB
      clean-history-on-start: true