server:
  port: 11000
  servlet:
    context-path: /authServer

spring:
  application:
    name: auth-server
#  sleuth:
#    sampler:
#      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web

management.tracing.sampling.probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

user-service:
  url: SP-USER-SERVICE/userService/

token:
  secretKey: tsk-32a0351c-7972-490f-8c94-e5d6c84abcdb
  # 1 hours
  expiredMillis: 3600000