server:
  port: 9000

spring:
  application:
    name: sp-gateway
  redis:
    host: localhost
    port: 6379
    password: 123456
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web
  output.ansi.enabled: always
  cloud:
    gateway:
      routes:
        - id: sp_product_route
          #uri: http://localhost:port
          # get from Eureka server
          uri: lb://sp-product-service
          predicates:
            - Path=/productService/**
          filters:
            - name: CircuitBreaker
              args:
                name: psFallback
                fallbackUri: forward:/productServiceFallback
#            - name: RequestRateLimiter
#              args:
#                key-resolver: "#{@pahtKeyResolver}"
#                redis-rate-limiter.replenishRate: 1000
#                redis-rate-limiter.burstCapacity: 1200
#                redis-rate-limiter.requestedTokens: 1
        - id: sp_user_route
          uri: lb://sp-user-service
          predicates:
            - Path=/userService/**
        - id: sp_order_route
          uri: lb://sp-order-service
          predicates:
            - Path=/orderService/**
        - id: sp_payment_route
          uri: lb://sp-payment-service
          predicates:
            - Path=/paymentService/**
        - id: auth_server_route
          uri: lb://auth-server
          predicates:
            - Path=/authServer/**
      default-filters:
        - name: CircuitBreaker
          args:
            name: globalFallback
            fallbackUri: forward:/defaultFallback
        ## global rate limiter
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@pahtKeyResolver}"
            redis-rate-limiter.replenishRate: 1000
            redis-rate-limiter.burstCapacity: 1200
            redis-rate-limiter.requestedTokens: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      registry-fetch-interval-seconds: 8
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,configprops

token:
  secretKey: tsk-32a0351c-7972-490f-8c94-e5d6c84abcdb

allowPath: /authServer/api/token,/productService/product,/productService/products