server:
  port: 9200
  servlet:
    context-path: /userService
spring:
  application:
    name: sp-user-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/sp-user
    username: postgres
    password: 123456
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web
  gson:
    date-format: yyyy-MM-dd hh:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output.ansi.enabled: always

logging:
  file:
    name: ../../logs/spUser.log
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 100MB
      total-size-cap: 100MB
      clean-history-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8
  instance:
    prefer-ip-address: true
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,configprops