server:
  port: 9004
  servlet:
    context-path: /paymentService
spring:
  application:
    name: sp-payment-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/sp-payment
    username: postgres
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    publisher-confirm-type: correlated
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web
  gson:
    date-format: yyyy-MM-dd hh:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8
  instance:
    prefer-ip-address: true

sp-order-service:
  url: SP-ORDER-SERVICE/orderService/