server:
  port: 11000
spring:
  application:
    name: spring-boot-admin

logging:
  file:
    name: ../../logs/sbAdmin.log
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 100MB
      total-size-cap: 100MB
      clean-history-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8
  instance:
    prefer-ip-address: true

