server:
  port: 8000
  tomcat:
    threads:
      max: 1000
spring:
  application:
    name: sp-web-site
  redis:
    host: localhost
    port: 6379
    password: 123456
  gson:
    date-format: yyyy-MM-dd hh:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output.ansi.enabled: always
  boot:
    admin:
      client:
        url: http://localhost:11000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,configprops

gateway:
  url: http://localhost:9000

allowPath: /login,/product,/actuator,/index