server:
  port: 8000
spring:
  application:
    name: sp-web-site
  redis:
    host: localhost
    port: 6379
    password: 123456
  gson:
    date-format: yyyy-MM-dd hh:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

gateway:
  url: http://localhost:9000
