server:
  port: 9090
spring:
  application:
    name: sp-web-site
  redis:
    host: localhost
    port: 6379
    password: 123456
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web
  gson:
    date-format: yyyy-MM-dd hh:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

gateway:
  url: http://localhost:9000/
