server:
  port: 9100
  servlet:
    context-path: /productService
spring:
  application:
    name: sp-product-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/sp-product
    username: postgres
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web
  gson:
    date-format: yyyy-MM-dd hh:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: http://localhost:9100/info
    healthCheckUrlPath: http://localhost:9100/health
    prefer-ip-address: true
