server:
  port: 9100
  servlet:
    context-path: /productService
  tomcat:
    threads:
      max: 500
spring:
  application:
    name: sp-product-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/sp-product
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 30
      connectionTimeout: 60000
  redis:
    host: localhost
    port: 6379
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
#    publisher-confirm-type: correlated
#    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web
  gson:
    date-format: yyyy-MM-dd hh:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output.ansi.enabled: always

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8
    health-check:
      enabled: true
  instance:
    prefer-ip-address: true
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,configprops